baseURL: https://limmia.github.io/
languageCode: en-us
title: Mia's blog
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: "286931502"
minify:
  disableXML: true
  minifyOutput: true
menu:
  main:
    - identifier: post
      name: Post
      url: /post/
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 2
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    # - identifier: Linkedin
    #   name: Linkedin
    #   url: https://www.linkedin.com/in/woojung-lim-432973167/
    #   weight: 30

defaultContentLanguage: kr
languages:
  # en:
  #   title: Mia's blog
  kr:
    title: 미아의 블로그
    contentDir: content
    languageName: 한국어
    weight: 2

staticDir:
- static